### PR TITLE
Remove unused JS files

### PR DESCRIPTION
**Pull request by ericthewry**
Hey @sf-interns/owners 

A long time ago, Peachy suggested that we remove all of our js files from the repo... we never did.
If you notice when you run `npm run devserve` the files that are bundled are entirely `*.coffee` files (except two.js).

I'm doing this from my PC, so try it on your machines to make sure it works

Note that this means you'll need to disable BetterCoffeeScript, or use sublime 3 where it doesn't compile.

### CODE REVIEW

**Comment by bmwwoo** [comment]
I would say to add all the js files to our .gitignore. There's definitely a way to make git still add our bundle js file though.

**Comment by ericthewry** [comment]
yeah. you can force it to recognize the bundle.js

**Comment by ericthewry** [comment]
@sf-interns/owners Let me know if there's anything else

**Comment by chuj** [comment]
LGTM :rocket:

**Pull request merged**
