### PR TITLE
Change to grid cell objects

### PR DESCRIPTION
**Pull request by bmwwoo**

### CODE REVIEW

**Comment by s-gogna** [comment]
LGTM :shipit:

**Comment by bmwwoo** [comment]
Looks amazing too

**Comment by ericthewry** [comment]
Doesn't look like a `GridCell` object got pushed.. Is that intentional--im not sure it would work without it?
Also the `GridCell` class should have an `isEmpty` method and thats what we should be testing in `GameGrid`, i.e. `grid[y][x].isEmpty`, not `grid[y][x].value =  ' '`

**Comment by shubhamgogna** [comment]
LGTM :rocket:

**Pull request merged**
