### PR TITLE
Change title to Math Brain

### PR DESCRIPTION
**Pull request by bmwwoo**

### CODE REVIEW

**Comment by chuj** [comment]
LGTM :+1:

**Comment by ericthewry** [comment]
Do we want Math Brain or MathBrain?  I was envisioning MathBrain

Thoughts @sf-interns/owners ?

**Comment by ericthewry** [comment]
Also, you'll need to change the CNAME

**Comment by bmwwoo** [comment]
@ericthewry I'm envisioning Math Brain. If it's MathBrain, when people search 'Math' or 'Brain', we'll be less likely to show up. The title 'Math Brain' is 10 characters and on mobile, that title appears fully on home screens.

The CNAME will change once we buy mathbrainapp.com or something. We still want mathswipe.com to still route to here correctly.

**Comment by ericthewry** [comment]
It seems like best practice to purchase mathbrain.com (or whatever's available) before we merge this in, and include the CNAME.

In terms of MathBrain vs Math Brain, the name doesn't significantly effect our play/app store SEO.

I don't have a _strong_ preference (I do think MathBrain is a little sleeker and hip-er).  What about you guys @chuj and @s-gogna ?

**Comment by chuj** [comment]
We might need to continue brainstorming for a name

If you search for "MathBrain" on Google Play, you'll see that there are a number of games called "MathBrain" or close variations of it.

I'm OK with having a name that is similar to a few other apps in the app store (if you search WordBrain you'll also find a lot of similar named apps), but we might want to find a new name that's less saturated in the app store.

What do you guys think?

**Comment by shubhamgogna** [comment]
@ericthewry I have a slight preference for `MathBrain`
@chuj brings up a good point. Do we need to reconsider the name?

**Comment by bmwwoo** [comment]
Closing in favor of "Math Swipe" instead.

**Pull request closed without merging**
